### ISSUE TITLE
New version of html5lib breaks old version of bleach

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/dyonisos#2]
requirements.txt states that bleach should be at least version 1.4.2. This version of bleach states (in its requirements.txt) that it needs at least version 0.999 of html5lib. Using version 0.9999999 of html5lib works. However, using version 0.999999999 of html5lib does not work.

The dirty workaround is to add html5lib==0.9999999 in requirements.txt above the line bleach==1.4.2. The neat way is to upgrade the version of bleach that we use.

**Comment by trolando** [comment]
I think upgrading bleach is a good idea, indeed.

**Comment by Pieter1024** [comment]
Fixed and pushed to master (and deployed in production)
